CREATE TABLE [dbo].[DOCTOR] (
    [DOCTOR]        INT           NOT NULL,
    [DOCTOR_NAME]   NVARCHAR (20) NULL,
    [DOCTOR_FAMIL]  NVARCHAR (20) NULL,
    [DOCTOR_MIDDLE] NVARCHAR (20) NULL,
    [OSMOTR]        CHAR (20)     NOT NULL,
    [USERID] INT NULL, 
    CONSTRAINT [PK_DOCTOR] PRIMARY KEY CLUSTERED ([DOCTOR] ASC),
    CONSTRAINT [FK_DOCTOR_OSMOTR] FOREIGN KEY ([OSMOTR]) REFERENCES [dbo].[OSMOTR] ([OSMOTR])
);

