CREATE TABLE [dbo].[TRENER] (
    [TRENER]        INT           NOT NULL,
    [TRENER_FAMIL]  NVARCHAR (20) NULL,
    [TRENER_NAME]   NVARCHAR (20) NULL,
    [TRENER_MIDDLE] NVARCHAR (20) NULL,
    [TRENEROVKA]    CHAR (10)     NOT NULL,
    [USERID] INT NULL, 
    CONSTRAINT [PK_TRENER] PRIMARY KEY CLUSTERED ([TRENER] ASC),
    CONSTRAINT [FK_TRENER_TRENEROVKA] FOREIGN KEY ([TRENEROVKA]) REFERENCES [dbo].[TRENEROVKA] ([TRENEROVKA])
);

